添加了关于环境变量的内容
rcore-os/rCore-Tutorial pull request #4
Opened 2020-06-28 11:45 UTC by JohnWestonNull

添加了关于`rust-objdump`安装后可能需要的环境变量配置，避免无谓的时间浪费。

2020-06-28 13:10 UTC, Tuyixiang requested changes
感谢补充，确实是一个新手容易遇到的问题。

不过有些小问题还需要处理：

- `$HOME` 需要大写
- 标题的 `rust-objdump` 应当使用代码格式
- English、`code` 等文字和两边汉字之间需要加空格。这个属于在仓库 `docs/format` 下面的一些关于文档排版的要求（不过没有仔细整理所以可能有点乱）

2020-06-28 13:36 UTC, JohnWestonNull commented
已经按照要求修改了格式，并且对第六部分加上了一个小修正。

2020-06-28 14:08 UTC, Tuyixiang requested changes
代码中使用的就是 `.globl`，这不是一个 typo

2020-06-28 14:24 UTC, JohnWestonNull commented
撤回了，能问一下为什么吗？

2020-06-28 14:35 UTC, Tuyixiang commented
> 撤回了，能问一下为什么吗？

`.globl` 和 `.global` 编译器都支持，使用前者可能是因为历史原因

2020-06-28 14:35 UTC, Tuyixiang approved these changes

2020-06-29 02:24 UTC, LyricZhao approved these changes

2020-06-29 02:24 UTC, LyricZhao approved these changes

2020-06-29 02:25 UTC, merged