windows wsl2的安装说明
rcore-os/rCore-Tutorial pull request #88
Opened 2020-07-19 10:13 UTC by stellarkey

更新了一些windows wsl2的安装说明。

2020-07-20 02:02 UTC, LyricZhao requested changes
感谢你的 PR，不过我们作为一个“书”类似的教程，希望做到规范。如果你觉得修改麻烦的话，可以暂时把这个分支放在这里，我有时间之后会基于你写的修改一遍。

2020-07-20 02:02 UTC, LyricZhao commented on docs/pre-lab/env.md
> +WSL（Windows Subsystem for Linux）是指Windows下构建linux环境（[Here](https://dowww.spencerwoo.com/)）。你可以在使用windows的同时，方便地进行linux下的开发，并且linux子系统上可以访问windows的文件系统。
1、中文和「英文、数字、符号」直接需要加入空格，而且 "linux" 并不是规范写法，请写 "Linux"；"windows" 需要写成 "Windows"；"win10" 也不是正式的写法，要写成 “Windows 10”；"wsl2" 要写成 "WSL 2"（有空格）；`winver` 两边如果不是标点符号，也需要空格；下面还有 "Ubutun" 的拼写错误；`记号` 只能用于代码，不用用于一个名词；不要出现英文括号，统一用中文括号；而且如果是运行的命令，请参考另外两个环境，加入一些 “运行命令” 的标记，而且要单独成行；还有一些标点的错误，也请修改一下。具体可以参考开发笔记中的规范文档，下面也有一些错误，敬请修正。
2、https://dowww.spencerwoo.com 在我这里无法访问，我推荐最好引用 Microsoft 官方的网站。

2020-07-20 02:02 UTC, LyricZhao commented on docs/pre-lab/env.md
> +  - `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`（启用windows功能：“已安装的虚拟机平台”）
我的理解是 `Enable-WindowsOptionalFeature` 和 `dism.exe` 是一个功能，为什么不统一用一个风格的命令呢？如果这两个有区别，也敬请指教，我对 Windows 系统不太熟悉。

2020-07-20 12:22 UTC, stellarkey commented on docs/pre-lab/env.md
> +  - `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`（启用windows功能：“已安装的虚拟机平台”）
哈哈哈，好的。会尽快修改。

关于命令风格的问题，当时只是搬运了一下网上的解法，没有研究具体的代码。：）太尴尬了。

2020-07-20 14:24 UTC, stellarkey commented
您好。已经修改。

另外，为什么第一个check老是红叉？这是否意味着不规范？

2020-07-21 01:38 UTC, LyricZhao commented
> 您好。已经修改。
> 
> 另外，为什么第一个check老是红叉？这是否意味着不规范？

这个 check 暂时是代码中的问题，不是你的问题，我们最近会修。

2020-07-21 01:39 UTC, merged